This is the error I gets trying to generate vector from our ms format sample without the header:



python makeFeatureVecsForSingleMsDiploid.py /home/khoih/fwdpy11test/data/test.txt 1100000 11 None all 0.25 None /home/khoih/fwdpy11test/data/test.txt.diploid.fvec
/home/khoih/anaconda3/envs/py36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
file name='/home/khoih/fwdpy11test/data/test.txt'Traceback (most recent call last):
  File "makeFeatureVecsForSingleMsDiploid.py", line 17, in <module>
    trainingDataFileObj, sampleSize, numInstances = openMsOutFileForSequentialReading(trainingDataFileName)
  File "/home/khoih/diploSHIC/msTools.py", line 139, in openMsOutFileForSequentialReading
    program,numSamples,numSims = header.strip().split()[:3]
ValueError: not enough values to unpack (expected 3, got 1)




The above error gets clear and vector file is generated after a header (fwdpy11 100 10) is added to the file test.txt. The new file with header is call test2.txt./
The vector file generated using test2.txt sample is test2.txt.diploid.fvec. However, when I try using predict function, I got the following error:




/home/khoih/anaconda3/envs/py36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "diploSHIC.py", line 265, in <module>
    np.reshape(testX,(testX.shape[0],nDims,numSubWins))
  File "/home/khoih/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 257, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/khoih/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 1280 into shape (10,11,11)




After generating different sample with different combination of number of sample and replicate, the error from predict function doesn't get clear up. In addition, I have tried /
generating new population simulation with mutation within interval position of [0,1). the same error occurs using the predict function of diploSHIC. However, when I tried deleting the/
last 7 stat name on the header line of the vector file ( the new file is called test3.txt.diploid.fvec), the predict function goes through the above error but kicks in another error:



/home/khoih/anaconda3/envs/py36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2018-05-08 07:54:52.141588: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loaded model from disk
Traceback (most recent call last):
  File "diploSHIC.py", line 285, in <module>
    preds = model.predict(validation_gen.standardize(testX))
  File "/home/khoih/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/training.py", line 1817, in predict
    check_batch_axis=False)
  File "/home/khoih/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/training.py", line 123, in _standardize_input_data
    str(data_shape))
ValueError: Error when checking : expected input_1 to have shape (12, 11, 1) but got array with shape (11, 11, 1)


 